### ISSUE TITLE
Feature request: Only application windows maximized and/or whitelist for windows hat don't need to be maximised 

### ISSUE THREAD

**Issue by Filbuntu** [aXe1/gnome-shell-extension-maximized-by-default#2]
Thank you for this helpful Gnome extension. It seems to work well on my system (Ubuntu 18.04). 
A logic side-effect is that EVERY window is maximized (except from the[ pop-up window from panel indicator qbirthday](https://ubuntuforums.org/showthread.php?t=2391594), I hoped it would also fix ). This means that even usual dialog and other desktop windows (e.g. the system or an application asking a question) and launchers (like Synapse, Albert) are maximised. 
Could this extension be tweaked to only open "normal" app windows maximised and/or include a whitelist for windows that don't need to be maximised?
Thanks again for your work on this great extension.

**Comment by matthijskooijman** [comment]
I would also be interested in this feature. I remember a window manager that I used a long time ago (probaly one of Awesome, i3 or xmonad, though I can't quite remember which) had a policy to keep dialog windows small / floating, though I do not know what it used to decide this.

I can imagine that any window that has a maximize button should be maximized, but I do not know if this is easy to detect? In the end, it's gnome-shell that decides whether to draw maximize buttons, so I guess an extension could figure this out?

**Comment by matthijskooijman** [comment]
I decided to dig into this a bit more. Lacking proper docks, I dug into the `gnome-shell` and `mutter` sources and found the `can_maximize` property that [controls whether the "maximize" option in the window menu (when right-clicking a titlebar) is enabled](https://gitlab.gnome.org/GNOME/gnome-shell/blob/3.32.0/js/ui/windowMenu.js#L41-42). This seems to be the right thing to check (since even when `can_maximize` is false, a window can still be forced to maximize but it will often not be too usable when dialogs or even toolbar overlay windows get maximized.

A possible trivial change to the implementation is below. It originally seemed that checking `can_maximize` was not sufficient, so I added some debug output to investigate other interesting properties, but it seems `can_maximize` is sufficient after all (I probably messed up a reload). 

```
    _windowCreatedId = global.display.connect('window-created', (d, win) => {
        log("New window [desc=" + win.get_description() +
            ", title=" + win.title +
            ", can_maximize=" + win.can_maximize() +
            ", decorated=" + win.decorated +
            ", window_type=" + win.window_type +
            "]")
        if (win.can_maximize())
            win.maximize(Meta.MaximizeFlags.HORIZONTAL | Meta.MaximizeFlags.VERTICAL)                                                                         
    });
```

I've seen that `can_maximize` is controlled by the [`has_maximize_func`](https://gitlab.gnome.org/GNOME/mutter/blob/3.32.2/src/core/window.c#L8461-8464) property in Mutter, which is set to false in various cases, such as [when a window is not a normal window](https://gitlab.gnome.org/GNOME/mutter/blob/3.32.2/src/core/window.c#L5731-5736) (alternatives are e.g. dialogs, [as listed here](https://gitlab.gnome.org/GNOME/mutter/blob/3.32.2/src/meta/window.h#L49-69)).

For interpreting the above debug output, you can find the X window id for a window (as returned by win.get_description()) using `xwininfo` (no clue how this works under wayland, though). The window types can be [found here](https://gitlab.gnome.org/GNOME/mutter/blob/3.32.2/src/meta/window.h#L49-69) (the listed types are sequentially numbered starting at 0).

**Comment by Filbuntu** [comment]
@matthijskooijman Thanks a lot for looking into this! This looks promising although I don't understand all of what you wrote 😉 . 
How can I or another layperson update the extension locally to get the new feature?
I tried to add your mentioned code text to the extension.js-file of this extension (and restarted the desktop as well as the system) but nothing changed.

**Comment by matthijskooijman** [comment]
> I tried to add your mentioned code text to the extension.js-file of this extension (and restarted the desktop as well as the system) but nothing changed.

That should be sufficient. For clarity, you need to edit 
`~/.local/share/gnome-shell/extensions/gnome-shell-extension-maximized-by-default@axe1.github.com/extension.js` and it should look like this:

```
const Meta = imports.gi.Meta;
  
let _windowCreatedId;

function enable() {
    _windowCreatedId = global.display.connect('window-created', (d, win) => {
        if (win.can_maximize())
            win.maximize(Meta.MaximizeFlags.HORIZONTAL | Meta.MaximizeFlags.VERTICAL)
    });
}

function disable() {
    global.display.disconnect(_windowCreatedId);
}
```

I left out the debug output here, since it should not be needed. Restarting gnome-shell after making a change to this file should be sufficient.

**Comment by Filbuntu** [comment]
Thanks for the quick clarification! I tried to just put the code you mentioned in your last post to the extension.js-file in the mentioned extension-folder, but some dialogue windows (e.g. save as/open file, ...) are still maximised. Then I added the previously mentioned code as well, it looks like this:  

```
const Meta = imports.gi.Meta;
  
let _windowCreatedId;

function enable() {
    _windowCreatedId = global.display.connect('window-created', (d, win) => {
        if (win.can_maximize())
            win.maximize(Meta.MaximizeFlags.HORIZONTAL | Meta.MaximizeFlags.VERTICAL)
    });
}

function disable() {
    global.display.disconnect(_windowCreatedId);
}

 _windowCreatedId = global.display.connect('window-created', (d, win) => {
        log("New window [desc=" + win.get_description() +
            ", title=" + win.title +
            ", can_maximize=" + win.can_maximize() +
            ", decorated=" + win.decorated +
            ", window_type=" + win.window_type +
            "]")
        if (win.can_maximize())
            win.maximize(Meta.MaximizeFlags.HORIZONTAL | Meta.MaximizeFlags.VERTICAL)                                                                         
    });
```

But still most of the windows are maximised, but for example the print dialogue not. Any other tip?

**Comment by matthijskooijman** [comment]
@Filbuntu, the code from my first post is not intended to be *appended* to the file, but it should replace the code in the `enable()` function (which is what I did in my second post). IIUC, you tried that and it still made some windows maximized, so perhaps these windows are "normal" windows after all and we need some other way to distinguish them. Can you be specific about what windows these are (e.g. in what application), so I can test them on my system as well?

Also, can you try putting the replacing the `extension.js` contents by this:

```
const Meta = imports.gi.Meta;
  
let _windowCreatedId;

function enable() {
    _windowCreatedId = global.display.connect('window-created', (d, win) => {
        log("New window [desc=" + win.get_description() +
            ", title=" + win.title +
            ", can_maximize=" + win.can_maximize() +
            ", decorated=" + win.decorated +
            ", window_type=" + win.window_type +
            "]")
        if (win.can_maximize())
            win.maximize(Meta.MaximizeFlags.HORIZONTAL | Meta.MaximizeFlags.VERTICAL)
    });
}

function disable() {
    global.display.disconnect(_windowCreatedId);
}
```

This is the modified code *and* the debug output. Then:
 - Open a terminal and run `journalctl -f | grep 'New window'`. This should show a single line of output whenever you open up a window
 - Open up a problematic window (e.g. that is maximized when it shouldn't) and see what the debug output says.
 - Paste the debug output line for that window here.

An example of such a line would be:

    jun 03 12:22:18 grubby gnome-shell[2826]: New window [desc=0x5200024, title=uxterm, can_maximize=true, decorated=true, window_type=0]

If you want to double-check what line corresponds to what window by running `xwininfo` in a second terminal and clicking a window. The terminal should then show a window id that corresponds with the id after `desc=`. Note that if you're running a Wayland session (which seems to be the default in newer distributions), this `xwininfo` stuff might not work.

**Comment by Filbuntu** [comment]
Thanks a lot! The "save as"-dialogues are usually maximised, here some examples (Ubuntu 18.04):
Evolution, save mail attachment:
Jun 03 12:30:00 ... gnome-shell[1982]: New window [desc=0x1e22f15 (Save Attac), title=Save Attachment, can_maximize=false, decorated=true, window_type=4]

Evolution, save mail as mbox:
Jun 03 12:31:12 ... gnome-shell[1982]: New window [desc=0x1e23717 (Save Messa), title=Save Message, can_maximize=false, decorated=true, window_type=4]

Firefox, save image as:
Jun 03 12:31:51 ... gnome-shell[1982]: New window [desc=0x3c00496 (Save Image), title=Save Image, can_maximize=false, decorated=false, window_type=4]

More to come when I have time again. Thank you very much for work on this.

**Comment by matthijskooijman** [comment]
@Filbuntu Ah! I see what happens here, I could reproduce it with the Firefox save dialog.

From the debug output, I see that the window has `can_maximize=false`, so the extension is not maximizing it (anymore). However, I suspect that the dialog remembers its previous size, position and also maximized state. So even though the extension is not maximizing the window now, gnome is. But since the window is not officially maximizable, you have no way to unmaximize it through the regular UI.

If you try this, I think it should work as expected again:

```
const Meta = imports.gi.Meta;

let _windowCreatedId;

function enable() {
    _windowCreatedId = global.display.connect('window-created', (d, win) => {
        log("New window [desc=" + win.get_description() +
            ", title=" + win.title +
            ", can_maximize=" + win.can_maximize() +
            ", decorated=" + win.decorated +
            ", window_type=" + win.window_type +
            "]")
        // See https://github.com/aXe1/gnome-shell-extension-maximized-by-default/issues/2
        if (win.can_maximize()) {
            win.maximize(Meta.MaximizeFlags.HORIZONTAL | Meta.MaximizeFlags.VERTICAL)
        } else {
            // Workaround for dialogs that were previously maximized by
            // us (when we did not check for can_maximize yet) and
            // remember their size.
            win.unmaximize(Meta.MaximizeFlags.HORIZONTAL | Meta.MaximizeFlags.VERTICAL)
        }

    });
}

function disable() {
    global.display.disconnect(_windowCreatedId);
}
```

This version explicitly unmaximizes windows that are not supposed to be maximized.

**Comment by Filbuntu** [comment]
Thanks for the quick update. Unfortunately it did not change the behaviour. Here some more examples:

Evolution save attachment:
Jun 03 13:33:12 ... gnome-shell[1779]: New window [desc=0x2006177 (Save Attac), title=Save Attachment, can_maximize=false, decorated=true, window_type=4]

Evince, save image:
Jun 03 13:34:37 ... gnome-shell[1779]: New window [desc=0x5a001a8 (Save Image), title=Save Image, can_maximize=false, decorated=false, window_type=3]

Evince, open document:
Jun 03 13:35:58 ... gnome-shell[1779]: New window [desc=0x5a00af8 (Open Docum), title=Open Document, can_maximize=false, decorated=false, window_type=3]

LibreOffice, open document:
Jun 03 13:40:08 ... gnome-shell[1779]: New window [desc=0x5c0a9d3 (Open), title=Open, can_maximize=false, decorated=false, window_type=4]

**Comment by Filbuntu** [comment]
Update. When I wanted to save an ethercalc-sheet, the first dialogue was minimised (question open or save):
Jun 03 15:00:28 ... gnome-shell[1779]: New window [desc=0x24009f3 (Opening o9), title=Opening o9rbqycwwudz.ods, can_maximize=false, decorated=true, window_type=3]

The second dialogue with the question where to save the spreadsheet was maximised:
Jun 03 15:00:49 ... gnome-shell[1779]: New window [desc=0x2400a06 (Enter name), title=Enter name of file to save to…, can_maximize=false, decorated=false, window_type=4]

Maybe this is helpful.

**Comment by matthijskooijman** [comment]
I just tried the evince dialogs, which are not maximized here. Are you sure these dialogs are maximized? Or are they just very big? IOW, can you drag the bottom right corner to make the window smaller?

**Comment by Filbuntu** [comment]
Thanks a lot for the hint, the windows I opened so far were indeed just very big and I could resize them which is remembered also with a system restart. 
As this code is really helpful, hopefully the extension can be updated. Not sure whether it is still maintained or the new behaviour is desired by the original developer, though.
@aXe1 Would you like to update the extension?

**Comment by matthijskooijman** [comment]
I've been running with the modification I suggested above for a while and I have not had any dialogs improperly maximized anymore, so it seems to work.

@aXe1, If you're interested, I can prepare a PR with this change?

**Comment by aXe1** [comment]
@matthijskooijman It would be great if u submit a PR. Currently I have no time to do any active work on pet projects, but there is no problem on just update the extension.

**Comment by matthijskooijman** [comment]
> It would be great if u submit a PR.

Done, see #4.

> Currently I have no time to do any active work on pet projects, but there is no problem on just update the extension.

Heh, familiar sentiment, I have too much of those projects too :-p Thanks for taking your time to respond regardless :-)

**Comment by aXe1** [comment]
@matthijskooijman Thank you for your work and patience!
PR merged, extension updated. Currently it is in unreviewed status, waiting for approve.

**Comment by aXe1** [comment]
FYI: new version got review, so it is now available for everyone.

**Comment by matthijskooijman** [comment]
@aXe1 Thanks!
